### ISSUE TITLE
Non-base58 character

### ISSUE THREAD

**Issue by johnsonchak** [project-serum/serum-rest-server#5]
I got an Error when i start the program. 
should i do any trasfer job to my private key which i export from sollet.io ?

**Comment by nathanielparke** [comment]
Hi @johnsonchak. The private key that you use should be in the base58 format. If you run `yarn shell` you can encode your array private key exported from sollet like so:

```
bs58 = require('bs58')
bs58.encode([.....])
```

**Comment by johnsonchak** [comment]
thanks, it works~
Btw,  i change the solona url to testnet and the server doesn't work as default url "https://solana-api.projectserum.com"
